### ISSUE TITLE
archive-level regression test functionality

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#101]
In https://github.com/KWARC/sTeX/issues/193 I have sketched the first ideas for regression testing in sTeX. I think I need MMT support for this. Maybe "need" is the wrong word, but regression testing support would be useful for other "regression-testing by repository" situations, like MMT.  

Here is the workflow I envision (using sTeX as an example and the ```HelloWorld/smglom``` repository). 
0. we make a new archive dimension ```test```, into that we copy all the generated OMDoc files in ```HelloWorld/smglom```  (preserving the directory structure) that we want to participate in the test. Alternatively, we can also write these OMDoc files by hand, if we cannot generate them yet. 
1. on every commit to the archive, ```travis``` builds ```HelloWorld/smglom``` and reports any build errors. 
 2. travis compares the contents of the ```test``` dimension to the build results and reports any discrepancies (we may need clever comparison tools here eventually)
3. If there are no discrepancies, then all is fine and travis exits successfully. 
4. If there are discrepancies the committer and the sTeX maintainer get notified and look at the differences.
5. If the discrepancies are legitimate/intended (e.g. when the sTeX bindings are improved and therfore yield better results), then we copy them to the ```test``` dimension (they become the new gold standard) and commit (thus restarting at 1.).  
6. if discrepancies are not legitimate/intendednot, we fix the sTeX bindings, commit and start at 1. again.  
I think that MMT should support this workflow to make regression testing easier and more common.

**Comment by kohlhase** [comment]
@m-iancu @florian-rabe please have a look and comment on this.

**Comment by kohlhase** [comment]
The example above works for OMDoc, since we can just compare XML files, but of course it works less well with PDF files that are more difficult to compare. Therefore we will need to make the comparison engines configurable.  

Of course, there is (as far as I know) no good way to compare two PDF files for "looking the same". Or at least I know of none. And what we would really need is a utility that compares the HTML generate from the OMDoc to see whether it looks the same as the PDF. Well, actually, we could generate derived versions from the PDF via pdf2ascii and html2ascii and compare them. That might actually be useful.

**Comment by kohlhase** [comment]
I have added the ```test``` dimension for ```HelloWorld/smglom``` (where all tests should be OK), so we have start developing here the MMT/travis functionality here.

**Comment by cmaeder** [comment]
Actually, for MMT the .omdoc files are committed to the corresponding content and narration repositories. After (re-)building I simply compare using `git diff`.

**Comment by cmaeder** [comment]
My current test scripts for MMT (called via `.travis.yml`) are in https://gl.mathhub.info/meta/inf/tree/master/config/MMT/testScripts. This directory also contains some massaged (wrt to the absolute file paths) expected output, i.e. of the sms generation.

The test data should maybe not clutter the actual user data (but we could make an exception for `HelloWorld` with test dimensions)

An actual latexml and pdflatex test is currently run via https://github.com/KWARC/localmh/blob/hello_test/bin/testHello.sh (not merged to master yet) without compare generated output file, though.

**Comment by cmaeder** [comment]
A command `mmt test [FILE_OR_FOLDER ...]` should trigger a corresponding `mmt make ....` command for those output files given by a separate `test` folder. Build failures and changes (wrt to output files within the test folder) will be reported.

Further commands `mmt add ...` and `mmt update ...` would add further test cases to or update the expected output in the test folder respectively.

**Comment by cmaeder** [comment]
`mmt add` would only make sense after a `mmt make`, since `mmt test` would not make new files.

**Comment by kohlhase** [comment]
actually, since ```mmt test``` triggers ```mmt make``` it makes changes after all, so ```mmt test add``` would make sense.

**Comment by kohlhase** [comment]
> Further commands mmt add ... and mmt update ...

I would propose to use ```mmt test add``` and ```mmt test update``` to keep things less messy at the top level.

**Comment by cmaeder** [comment]
The current setup is as follows:

 - `mmt make <target> --force --test ...` builds the target and outputs a diff between the output file and a corresponding test file (if it exists).

- without the `--force` option only files are compared that are actually rebuilt (but not files that are up-to-date).

- with the additional options `--test-update` (or `--test-add`) differing (or non-existing) test files are overwritten (or newly created).

- the options `--test-update` and  `--test-add` also work without `--test` (and without rebuilding). In this case output files are simply copied into the test dimension. (Currently, out-of-date files are rebuilt after copying unless the option `--dry-run` is also given to prevent rebuilding.) 

- Maybe missing is an option `--test-diff` that only calls `diff` (without building); and also missing are options to control the `diff` program.

**Comment by kohlhase** [comment]
I am trying this out now, it would be very good if the diff would also tell me  what file it is currently referring to.

**Comment by kohlhase** [comment]
sorry, I understand this now.

**Comment by kohlhase** [comment]
is there a diff.log file? That would be very good to have, then I can remove all the problems when I have checked they are OK.

**Comment by kohlhase** [comment]
ideally a file in a standard format that emacs can show to me als diff markup.

**Comment by cmaeder** [comment]
Instead of displaying the diff I now create a`.diff` file under the test folder. (The option `--test` does create diffs even for files that are not newly build, i.e. when run with `--dry-run`.)
