### ISSUE TITLE
mmt make alltex/pdflatex should also go into tikz subdirs

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#105]
The title says it all. They currently do not.

Even more crucially, we need the ```localpaths.tex``` files in ```tikz``` subdirs as
well. I have the feeling that it might be a good idea to introduce a separate ```mmt
make``` target ```localpaths``` and make the targets ```pdflatex```, ```latexml```, and
```alltex``` on it.

**Comment by cmaeder** [comment]
I think I've got a patch https://github.com/KWARC/MMT/commit/bd0bee6e410f1e1c409caeb254858b90e4d8222d that traverses `tikz` folders, but I need to wait for travis to succeed before I can merge this to master. Only then it will be part of gh-pages and used by lmh after update.

I made no separate target `localpaths`, yet.

**Comment by cmaeder** [comment]
You can now play with MMT. (`localpaths.tex` files are still created as needed or taken as given.)

**Comment by cmaeder** [comment]
I close this, reopen it or make a new issue if a separate localpaths target is needed

**Comment by kohlhase** [comment]
I do not care about the separate target, if I get the files ```localpaths.tex``` automatically whenever I need them. I will complain again, ... if I do not.
