### ISSUE TITLE
New build target allpdf

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#106]
I would like to have a new build target ```allpdf``` for ```mmt make```  that depends on
the ```alltex``` target and then runs pdflatex over ```all.tex``` and ```all.*.tex``` to
generate overview PDFs. Naturally, this should also go into the tikz folders.

**Comment by cmaeder** [comment]
The target `allpdf` already exists, but `tikz` folders are not traversed.
Also the `alltex` target does not traverse `tikz` folders.

Do you have an example repository where you need `all.tex` files within `tikz` folders.

I could simply drop not traversing `tikz` folders for `alltex` and `allpdf`.

Maybe there is a better way to exclude certain directories via META-INF/MANIFEST.MF entries.

**Comment by kohlhase** [comment]
> I could simply drop not traversing tikz folders for alltex and allpdf

yes, only ```sms``` and ```omdoc``` should not be run on ```tikz``` folders.

**Comment by kohlhase** [comment]
> Do you have an example repository where you need all.tex files within tikz folders.

any tikz folder would do. How about ```MiKoMH/talks/source/ODK/tikz```.

**Comment by cmaeder** [comment]
just to let you know, I've pushed this change MiKoMH/talks:

```
--- a/source/ODK/en/interface-theories.tex
+++ b/source/ODK/en/interface-theories.tex
@@ -20,8 +20,8 @@
       Open standard knowledge base \red{with interface theories}
       \begin{center}
         \begin{tabular}{c@{\hspace{1cm}}c}
-          \mhtikzinput{odk/tikz/mstargraph} & 
-          \mhtikzinput{odk/tikz/mistargraph}
+          \mhtikzinput{ODK/tikz/mstargraph} &
+          \mhtikzinput{ODK/tikz/mistargraph}
         \end{tabular}
       \end{center}
```

**Comment by kohlhase** [comment]
thanks this is great.

**Comment by cmaeder** [comment]
I close this issue, since all will be resolved by https://github.com/KWARC/MMT/issues/105
