### ISSUE TITLE
pdflatex make target has too many dependencies

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#112]
I ma building ```MathHub/MiKoMH/GenCS/source/www/en/reluri.tex``` with ```pdflatex```, and ```mmt make``` runs ```pdflatex``` on all the files that are included. But the pdf only depends on the sms files. 
Something is wrong.

**Comment by cmaeder** [comment]
fixed by the changes in `STeXAnalysis.scala` of https://github.com/KWARC/MMT/commit/2ea354254238f92e3e625159ce5607b112af3661
