### ISSUE TITLE
mmt does not traverse a group directory that contains a meta-inf repository with a MANFEST.MF file on a mac

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#114]

**Comment by cmaeder** [comment]
only within a docker!

**Comment by cmaeder** [comment]
@tkw1536 the file `MathHub/smglom/meta-inf/MANIFEST.MF` can no longer be distinguished from
`smglom/smglom/META-INF/MANIFEST.MF` (in order to detect an MMT archive).

The workaround was to (re)move the `meta-inf/MANIFEST.MF` file

**Comment by tkw1536** [comment]
This is not a problem inside localmh. I can read META-INF/MANIFEST.MF files inside docker without a problem (and I can check they exist also). I don't think we should not rely on case-sensitivity to check if something is an archive.

**Comment by cmaeder** [comment]
@kohlhase In order to avoid relying on the case of `meta-inf` (repo) vs `META_INF` (folder) the `MANIFEST.MF` files in `meta-inf` repositories should be moved down to `META-INF/MANIFEST.MF` (or should be renamed differently)

**Comment by kohlhase** [comment]
I think you should talk about this with Mihnea, I am fine with whatever works.

**Comment by m-iancu** [comment]
If we do `meta-inf/META-INF/MANIFEST.MF` then the meta-inf repo itself will be treated as an archive. That means it's config inside will apply to the repository itself rather than the group according to MMT understanding. In a way it's MMT's fault, META-INF and MANIFEST.MF files are not really an MMT-specific thing, so MMT should probably check the content of the manifest before assuming it's an MMT archive and not something else (e.g. an extracted jar)

**Comment by cmaeder** [comment]
For which key should MMT look inside the MANIFEST.MF file in order to decide for an archive? `id` is no longer needed as it defaults to `group/repo`. 

I could check if there is also a `.git` directory (that is usually not in a group directory).

**Comment by m-iancu** [comment]
We could also rename `MANIFEST.MF` to something else,(e.g.  `GROUP_MANIFEST.MF`) this would be less disruptive and only MathHub uses it as far as I know. So I could change it quickly and be done

**Comment by cmaeder** [comment]
That would be excellent!

**Comment by m-iancu** [comment]
This is essentially fixed. If I missed a group you can let me know. I patched the mathhub code accordingly.
