### ISSUE TITLE
further error viewer enhancements

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#127]
- the source link should be given for "file name" to show the content in a text window, and add
a link to gl.mathhub.info to edit it.
- remove "error type" and "archive" columns.
- the content column should become a link to the "error level" values
   (can we have a fragment reference that goes to the correct error?)
- from/to selector for "modified"

**Comment by kohlhase** [comment]
Oh, and another one: bind the "return" key to reload that would be very helpful.

**Comment by cmaeder** [comment]
Pressing return in a text field (or the max. number field) reloads now.
From the above points only error-fragments and "modified" (selecting older or newer dates) are not addressed yet.

**Comment by cmaeder** [comment]
Currently I create links to gl.mathhub.info that might not exist (when either the sources are not there or the "in-dimension" is not `source`).

**Comment by cmaeder** [comment]
There are now "older" and "newer" (or equal) selectors for "modified" (if checked) as well as the simple former "contains"  option that always matches if the search string is empty. ("newer" with the empty search string also matches every date.)

**Comment by cmaeder** [comment]
Meanwhile, only "newer" (and equal) or "older" dates can be matched.
