### ISSUE TITLE
sTeX importer fails completely with new queue

### ISSUE THREAD

**Issue by m-iancu** [KWARC/MMT#133]
A `println` at the beginning of the `importDocument` method (implementing `Importer` class) shows it's never actually called. 
With `--noqueue` option everything goes smoothly. The `Update` option is `-1` (Force). 
@cmaeder  not sure if the issues is with the importer itself or with the new build queue.

**Comment by m-iancu** [comment]
@akbar you can switch back to running without `--noqueue` when this issue is fixed.

**Comment by cmaeder** [comment]
How should I reproduce the problem? I get:

```maeder@lati:/var/data/localmh/MathHub/smglom/mv$ /var/data/localmh/ext/MMT/deploy/mmt.jar make stex-omdoc --force
error: Skipping declaration-level element `symbol` due to unexpected error
error: Skipping declaration-level element `symbol` due to unexpected error
error: Skipping declaration-level element `symbol` due to unexpected error
error: Skipping declaration-level element `symbol` due to unexpected error
error: Skipping declaration-level element `symbol` due to unexpected error
error: Skipping declaration-level element `symbol` due to unexpected error
error: Invalid notation rendering
error: Invalid notation rendering
```

**Comment by cmaeder** [comment]
With `--noqueue` I get the output twice. This means the "running twice" trick of the importer no longer works.

**Comment by cmaeder** [comment]
Unfortunately, the queue is designed to avoid building stuff that is already built.

**Comment by m-iancu** [comment]
even with the `--force` option ?

**Comment by cmaeder** [comment]
An "exit" at the end of a `build.msl` file prevents an actions of the asynchronous build queue.
