### ISSUE TITLE
inputref should not make a dependency

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#134]
I see that if a file ```bar.tex```, then lines ```\inputref{foo}``` and ```\mhinputref{foo}``` result in a rebuilding of their ```sms``` files. 
That is not correct, there is no dependency there. 
BUT, ```bar.tex``` is not up-to-date, if one of the inputref-ed files it not.

**Comment by cmaeder** [comment]
So `bar.omdoc` (or `bar.pdf`) does not depend on `foo.sms` but on `foo.tex` only.

**Comment by kohlhase** [comment]
> So bar.omdoc (or bar.pdf) does not depend on foo.sms but on foo.tex only.
yes. But I am not sure whether it is the best strategy to directly rebuild ```foo.tex```, since this is only a transclusion dependency, (or did we call it a file depencency?).

**Comment by cmaeder** [comment]
It is a plain physical (file) dependency. It looks as if the dependency treatment of `\mhinputref` and `\usemhmodule` is simply mixed up.

**Comment by kohlhase** [comment]
is there a file what states the dependencies that I would proofread? It would be good documentation as well.

**Comment by cmaeder** [comment]
`\inputref` is also not considered at all.

**Comment by cmaeder** [comment]
currently I've only code an no documentation.

**Comment by kohlhase** [comment]
is there a way to generate the code from a declarative config file? That would be useful in the longer run.

**Comment by kohlhase** [comment]
but that is a separate issue I guess.

**Comment by cmaeder** [comment]
The currently considered keywords/regexps are in https://github.com/KWARC/MMT/blob/master/src/mmt-stex/src/info/kwarc/mmt/stex/STeXUtils.scala (line 80 to 102)

**Comment by cmaeder** [comment]
The ugly code for the dependency computation is in https://github.com/KWARC/MMT/blob/master/src/mmt-stex/src/info/kwarc/mmt/stex/STeXAnalysis.scala "matchPathAndRep" (line 57-85)
