### ISSUE TITLE
\usemodule should make a sms dependency 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#135]
```\usemodule[load=foo]{...}``` should make a dependency on ```foo.sms``` and 
```\usemhmodule[repos=foo,path=bar]{...}``` should make one on ```foo/source/bar.sms```

Both do not seem the case right now.

**Comment by kohlhase** [comment]
I have tested that with a new module which I directly "used" in another module.

**Comment by cmaeder** [comment]
Right, `\usemhmodule` only seems to add a dependency on `foo/source/bar.tex`

**Comment by cmaeder** [comment]
`\usemodule` is currently not supported at all (and only occurs in `MiKoMH/GenCS/source/adt/en/adt-def.tex`)

**Comment by kohlhase** [comment]
hmmm, it should be supported (and is an error in adt-def.tex). Do we support ```\importmodule```?

**Comment by kohlhase** [comment]
> (and is an error in adt-def.tex)

actually I retract that. It is OK.

**Comment by cmaeder** [comment]
`\importmodule` is not considered for dependencies but copied into .sms files.

**Comment by kohlhase** [comment]
```\importmodule``` and ```\usemodule``` should create the same dependencies like ```\importmhmodule``` and ```\usemhmodule``` in sTeX files, but with different arguments. 
```\importmhmodule[repos=foo,path=bar]{baz}``` is the same as ```\importmodule[load=<MathHubBase>/foo/source/bar]{baz}``` and analogously for ```\usemhmodule```.

**Comment by cmaeder** [comment]
should '\importmhmodule` and `\usemodule` produce the same dependencies? Currently only '\importmhmodule` produces a dependency on the corresponding .sms file.

**Comment by kohlhase** [comment]
All four (actually six as we have the variants ```\guse``` and ```\gimport``` as well) should create a  dependency to the corresponding module signature (usually a ```*.sms``` file, but in SMGloM a ```*.tex``` file with a ```modsig``` environment). I think that the ```use``` variant creates a file dependency and the ```import``` variant a logical dependency. Let me see if I got this right. 

The difference is the in the recursive behavior. Say we have a file ```foo.tex``` 
```
\begin{modsig}{foo}
\gimport{bar}
\guse{baz}
\end{modsig}
```
then a logical dependency on ```foo.tex``` should recurse into ```bar.tex``` but not into ```baz.tex```.

**Comment by cmaeder** [comment]
Currently, I do not distinguish if I'm in SMGloM or not. How should I? I either create a build dependency (on a .sms file) or a physical file dependency (on a .tex file). A logic dependency would refer to a module (that are created by stex-omdoc, I guess). 

What are the direct dependencies for creating a .pdf (or .omdoc) file from a .tex file containing any of the six variants?

**Comment by kohlhase** [comment]
all six create a dependency on the corresponding module signature (i.e. that needs to be re-built, if not up-to-date). But what the module signature is is different for all six: 
```
\importmodule[load=foo]{} --> foo.sms
\importmhmodule[repos=foo,path=bar]{} --> foo/source/bar..sms
\gimport[foo]{bar} --> foo/source/bar.tex
```
and the same for the ```use``` variants.

**Comment by cmaeder** [comment]
The current `\importmodule` occurrences that I found are:

```
./MiKoMH/talks/source/sTeX/ex/sTeX-modules-ex.tex:  \importmodule{pairs}
./MiKoMH/talks/source/sTeX/ex/sTeX-modules-ex.tex:  \importmodule{sets}
./MiKoMH/talks/source/sTeX/ex/sTeX-modules-ex.tex:  \importmodule{setoid}
./MiKoMH/talks/source/physml/en/stex.tex:  \importmodule{dimensions}
./MiKoMH/GenCS/source/adt/en/adt-def.tex:      \importmodule{adt-uNat}
```

**Comment by kohlhase** [comment]
Yes, I know, I have optimized all \import and \use to the mh variants in the collections because that makes them easier to manage. But in general sTeX can have all forms, so we must support them.
