### ISSUE TITLE
encoding problem in short error message in errorviewer

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#138]
in the error viewer we see error messages like
```
latexml-compiler: malformed:omdoc:notation &lt;omdoc:notation&gt; isn't allowed here 
```
there is a problem with the encoding of < and >.

**Comment by cmaeder** [comment]
Right, this happens, because the message is an attribute value inside the xml .err file

**Comment by kohlhase** [comment]
But I am sure that this can be fixed, no?

**Comment by cmaeder** [comment]
Yes, I need to search for an html decoder.

**Comment by kohlhase** [comment]
how about 
```
sed "s/&gt;/>/g s/&lt;/</g"
```

**Comment by cmaeder** [comment]
I don't want to program it myself, but if I would use scala and not `sed`. Potentially there are many more html encoded sequences.

**Comment by cmaeder** [comment]
the fix was trivial (after discovering the difference between `NodeSeq.text` and `Seq[Node].toString`)
