### ISSUE TITLE
errorviewer: target restriction should also affect most common errors

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#139]
I vaguely remember that at one time the selection of the target (or other columns) also restricted the most common errors on top, it does not seem to do that any more (and I want it back).

**Comment by cmaeder** [comment]
This did work well together with selecting of any (and switching between) the common errors that also fills a search field (that for the short message).

The group window can currently only be restricted by hiding certain entries which is cumbersome for your use case.

**Comment by cmaeder** [comment]
I'll will ignore the additional restriction by the short message for the group window, then.

**Comment by cmaeder** [comment]
`lmh setup --update` should now get the improved version from `master-binaries`
