### ISSUE TITLE
MMT build queue page should have "report issue", "help" and links 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#140]
When the queue is big, it would  be very helpful to have links to "finished" and "blocked".

**Comment by kohlhase** [comment]
Oh, and it would be great, if somewhere on the top the length of the current qeue was given.

**Comment by cmaeder** [comment]
the length was supposed to show up after the string "queue length" (but the angularjs value computed was wrong, actually wrongly typed without any obvious problem indication)
