### ISSUE TITLE
no not remove latexml omdoc output file in case of failures

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#143]
@kohlhase @m-iancu in https://github.com/KWARC/MMT/blob/master/src/mmt-stex/src/info/kwarc/mmt/stex/LaTeXML.scala (line 363) I `lmhOut.delete` the omdoc output file in case of `failure`.

Failures are a non-zero exit code, an empty omdoc file or a scala exception. Should I keep the file?

**Comment by cmaeder** [comment]
I assume that a non-zero exit code of calling latexml always corresponds to a `fatal error` shown in the corresponding `.ltxlog` file.

**Comment by kohlhase** [comment]
I am not sure. please test.

**Comment by cmaeder** [comment]
My assumption was wrong, plain errors also lead to a non-zero exit code. The resulting `.omdoc`file may still be useful (or corrupt).
