### ISSUE TITLE
let build queue use less resources

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#148]

**Comment by cmaeder** [comment]
- not all queue entries need to be shown
- decrease the refresh rate after some time

**Comment by cmaeder** [comment]
every 20 refreshes the time between refreshes doubles now and at most a hundred queue entries are shown (only 50 if the queue is longer).  At the bottom of the queue the number of entries is given that are not shown.

**Comment by kohlhase** [comment]
very good, but maybe there should be a button to reset the queue to "fast mode".

**Comment by cmaeder** [comment]
Simply reloading will do this.

**Comment by cmaeder** [comment]
Currently http://pine.eecs.jacobs-university.de:8080/buildqueue.html (and the matching error viewer with "clean" and "rebuild" buttons) could be observed.

(It should be possible to disable those server actions that may clean or modify generated content.)
