### ISSUE TITLE
spurious blanks in glossary 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#152]
In  ```smglom/algebra/latexml/commutative.omdoc``` we have an example: a blank before the final . 
look for commutative in the glossary. 
The OMDoc seems OK: 
```
<omdoc:term cd="commutative" name="commute" xml:id="commutativeproperty.def.CMP1.p1.term8" about="#commutativeproperty.def.CMP1.p1.term8" stex:srcref="smglom/algebra/source/commutative.en.tex#textrange(from=5;1,to=6;41)">commute</omdoc:term>.</p></omdoc:CMP>
```

**Comment by m-iancu** [comment]
fixed

**Comment by kohlhase** [comment]
very good to hear this. When are you going to re-generate the glossary?

**Comment by m-iancu** [comment]
fixing a number of issues now, will commit and redeploy everything once I'm done (tonight/tomorrow)

**Comment by kohlhase** [comment]
thanks, looking forward to this.
