### ISSUE TITLE
presentation of applications without notation definitions wrong for SMGloM

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#153]
In ```smglom/calculus/metric-space.omdoc``` we have 
```
	<om:OMA>
	  <om:OMV name="d"/>
	  <om:OMV name="&#x1D465;"/>
	  <om:OMV name="&#x1D466;"/>
	</om:OMA>
```
and that is presented as ```(d x y)```. This is OK for MMT, but should be ```d(x,y)``` for the glossary.

**Comment by m-iancu** [comment]
fixed
