### ISSUE TITLE
missing latexml dependencies

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#160]
In the glossary we have files like ```graphincidence.en.tex``` where the latter contains the line 
```LaTeX
\begin{mhmodnl}[creators=hwk]{graphincidence}{en}
```
this constitutes a dependency from ```graphincidence.tex```, which does not seem to be realized in the queue. This dependency has to be added.

**Comment by cmaeder** [comment]
Right, `\begin{mhmodnl}` was never considered, yet. Should it be treated like `\begin{modnl}`?

**Comment by cmaeder** [comment]
I noticed this problem also in `helloworld.de.tex`.

**Comment by kohlhase** [comment]
> Right, \begin{mhmodnl} was never considered, yet. Should it be treated like \begin{modnl}?

yes.

**Comment by cmaeder** [comment]
done by https://github.com/KWARC/MMT/commit/f63017059804634bda20229ffffeef85927d2148
