### ISSUE TITLE
extend sms generation and dependencies for structure and gstructure 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#162]
At the moment we only look at ```\importmodule```, ```\importmhmodule```, and ```\gimport``` in SMS generation. But we now also have the ```sstructure```, ```mhstructure```, and ```gstructure``` environments. E.g. in ```MathHub/smglom/algebra/source/ring``` we have 
```LaTeX
  \begin{gstructure}{add}{cgroup}
    \tassign{op}{addition}
    \tassign{inv}{subtraction}
    \tassign{unit}{zero}
  \end{gstructure}
```
We need to extend ```sms``` generation and dependencies in the following way: 
 * ```\begin{gstructure}[foobar]{foo}{bar}``` should be treated like a ```\gimport[foobar]{bar}```. 
 * ```\begin{mhstructure}[foo]{bar}{baz}``` should be treated like ```\importmhmodule[foo]{baz}``` 
 * ```\begin{sstructure}[foo]{bar}{baz}``` should be treated like ```\importmodule[foo]{baz}```.
all the rest can be dropped.

**Comment by cmaeder** [comment]
Right, this is to be implemented in `createSms` (line 120 of https://github.com/KWARC/MMT/blob/master/src/mmt-stex/src/info/kwarc/mmt/stex/STeXAnalysis.scala) after `smsRegs` are extended accordingly.

**Comment by kohlhase** [comment]
Oh, and while we are at it, we also need treatment for views: 
* ```\begin{gviewsig}[fromrepos=FOO,torepos=BAR]{foobar}{foo}{bar}``` should be treated like ```\gimport[FOO]{bar}\gimport[BAR]{baz}```. 
* ```\begin{gviewnl}[...]{foo}{en}{bar}{baz}``` should be treated like ```\gimport{foo}```.
* ```\begin{view}[from=FOO,to=BAR]{foo}{bar}``` should be treated like ```\importmodule[load=FOO]{foo}\importmodule{load=bar]{BAR}```
* ```\begin{mhview}[fromrepos=FOO,frompath=FOOP,torepos=BAR,toreposBARP]{foobar}{foo}{bar}``` should be treated like ```\importmhmodule[repos=FOO,path=FOOP]{bar}\importmhmodule[repos=BAR,path=BARP]{baz}```
* ```\begin{view}[from=FOO,to=BAR]{foo}{bar}``` should be treated like ```\importmodule[FOO]{foo}\importmodule[BAR]{bar}```.

**Comment by cmaeder** [comment]
`\begin{view}[from=FOO,to=BAR]{foo}{bar}` is duplicated with slightly different treatments

**Comment by cmaeder** [comment]
> \begin{gstructure}[foobar]{foo}{bar} should be treated like a \gimport[foobar]{bar}.

the part `[foobar]` is optional and not given in `MathHub/smglom/algebra/source/ring.tex`.
The current repository is used then (`\mhcurrentrepos{smglom/algebra}`).

**Comment by cmaeder** [comment]
`MathHub/smglom/sets/source/linear-order-lexord.en.tex` contains 

```
\begin{gviewnl}[creators=miko]{linear-order-lexord}{en}
  {linear-order}{lexical-order}
```

Since I only match line-wise, I'll only match for the first argument that is enough for `gviewnl`.

**Comment by cmaeder** [comment]
Also `gviewnl` may have the `fromrepos` attribute.

**Comment by cmaeder** [comment]
`\begin{gviewnl}[creators=miko,fromrepos=smglom/sets]{linear-order-natlessthan}{de}` from `smglom/numberfields/source/linear-order-natlessthan.de.tex` should be turned into `\gimport{linear-order-natlessthan}`? 

`\begin{gviewnl}[creators=miko,fromrepos=smglom/algebra]{group-intplus}{de}`
from `smglom/numberfields/source/commutativering-intplustimes.de.tex` seems wrong (no file `group-intplus.tex`. 

Same for `\begin{gviewnl}[creators=miko]{ordering-subword}{de}` from `smglom/sets/source/order-subword.de.tex`

**Comment by kohlhase** [comment]
> \begin{view}[from=FOO,to=BAR]{foo}{bar} is duplicated with slightly different treatments

the first one is correct, please disregard the second.

**Comment by kohlhase** [comment]
> the part [foobar] is optional and not given in MathHub/smglom/algebra/source/ring.tex.
> The current repository is used then (\mhcurrentrepos{smglom/algebra}).

correct.

**Comment by kohlhase** [comment]
> Since I only match line-wise, I'll only match for the first argument that is enough for gviewnl.

if at all possible we should (always) allow multiple lines and whitespace between the arguments.

**Comment by kohlhase** [comment]
> \begin{gviewnl}[creators=miko,fromrepos=smglom/algebra]{group-intplus}{de}
> from smglom/numberfields/source/commutativering-intplustimes.de.tex seems wrong (no file group-intplus.tex).

there are multiple issues here, first is a c/p error (fixed in the source) and then the arguments of ```gviewnl``` are misdesigned, see https://github.com/KWARC/sTeX/issues/222

**Comment by kohlhase** [comment]
> Same for \begin{gviewnl}[creators=miko]{ordering-subword}{de} from smglom/sets/source/order-subword.de.tex

same here, fixed in the source

**Comment by kohlhase** [comment]
> \begin{gviewnl}[creators=miko,fromrepos=smglom/sets]{linear-order-natlessthan}{de} from smglom/numberfields/source/linear-order-natlessthan.de.tex should be turned into \gimport{linear-order-natlessthan}?

yes

**Comment by cmaeder** [comment]
for `view` (wrongly) and `sstructure` (as requested) I currently generate an `\importmodule[...]` without `load=...` entry. 

All other `load` arguments for `\importmodule` are absolute paths and there is always an `ext=` entry, too.

Under MathHub I do not find `sstructure` examples and only probably deprecated `view`s.

```
./KwarcMH/SiSsI/source/winograd/cds/linearextrapolation.tex:\begin{view}[from=\MathHub{KwarcMH/SiSsI/source/winograd/cds/prognosis}]{prognosis}{linearextrapolation}
./KwarcMH/SiSsI/source/winograd/cds/crystalball.tex:\begin{view}[from=\MathHub{KwarcMH/SiSsI/source/winograd/cds/prognosis}]{prognosis}{crystalball}
./KwarcMH/SiSsI/source/winograd/cds/average-prognosis.tex:\begin{view}[from=\MathHub{KwarcMH/SiSsI/source/winograd/cds/prognosis}]{prognosis}{average-prognosis}
```

What should be changed?
