### ISSUE TITLE
port python code for sms generation to scala

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#17]
MMT should generate sms files

**Comment by tkw1536** [comment]
@cmaeder  The code for generating sms files in in these lines: 

https://github.com/KWARC/localmh/blob/master/lmh/lib/modules/generators/sms.py#L33-L53

Some of the variables are intialised at the top of the file. If you have any questions, let me know.

**Comment by cmaeder** [comment]
Should be fixed by https://github.com/KWARC/MMT/commit/1c1dea8a8454b6d797d894227424b0510b90e6d6
