### ISSUE TITLE
combine running latexml and stex-omdoc

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#27]

**Comment by cmaeder** [comment]
stex-omdoc is run twice. @m-iancu does this make sense to do for a single file?

**Comment by m-iancu** [comment]
Its because of dependencies. I'm not sure how it can work on a per-file basis because e.g. signatures and language bindings depend on each-other, so rebuilding just one file (ignoring deps) will probably not work well.

**Comment by cmaeder** [comment]
So even wholly running over one archive might not be enough, since dependencies may be in other archives?

**Comment by cmaeder** [comment]
smglom/sets and smglom/mv are mutually depended on each other

**Comment by m-iancu** [comment]
In principle yes, and thats why I run twice I think. But the biggest issue is between signatures `*.tex` and language bindings `*.<lang>.tex` and those "language groups" are always (to my knowledge) in the same archive. Other dependencies are only used to resolve ambiguous references, but the defaults are usually good enough.

**Comment by cmaeder** [comment]
This is implemented in https://github.com/KWARC/MMT/commit/10dd99cdec828af9230ce3546e78a351eca73a8c The target name is `latexml-stex-omdoc`
