### ISSUE TITLE
do not build in tikz subdirectories

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#31]
we need a way to turn off building sms and omdoc in ```tikz``` subdirectories

**Comment by cmaeder** [comment]
I've tried to override `includeDir` from https://github.com/KWARC/MMT/blob/svn-mirror/src/mmt-api/trunk/src/main/info/kwarc/mmt/api/archives/BuildTarget.scala (line 142), but this method is never used (and could be deleted).

The actual `includeDir` method that controls traversing is in https://github.com/KWARC/MMT/blob/svn-mirror/src/mmt-api/trunk/src/main/info/kwarc/mmt/api/archives/Archive.scala (line 56 and used in line 97), but I do not know how to override this method from https://github.com/KWARC/MMT/blob/svn-mirror/src/mmt-stex/src/info/kwarc/mmt/stex/LaTeXML.scala

**Comment by cmaeder** [comment]
Could I simply hard-code to always skip `tikz` directories?

**Comment by cmaeder** [comment]
Florian suggested to pass the yet unused `includeDir` method as additional argument to `traverse` and group many of the arguments of traverse into one argument.

**Comment by cmaeder** [comment]
fixed by https://github.com/KWARC/MMT/commit/38f68665ee92ccb31056945f40961d18285d0066
