### ISSUE TITLE
setup test infrastructure

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#35]
Mark added tests to mmt-leo. However, I do not thing that classes (needing scalatest_2.11-2.2.4.jar) should go into the finally deployed jar.

Only tiscaf seems to have the recommend directory layout for tests (see http://www.scala-sbt.org/0.13/docs/Testing.html).

In fact, I've rename https://github.com/KWARC/MMT/blob/stable/src/tiscaf/src/test/scala/tiscaf/test/TestServerOk.scala.fixed to avoid a dependency on scalatest so far.

**Comment by cmaeder** [comment]
`scalatest` is also imported in some (old) mmt-api test sources that I currently excluded by helplessly setting `scalaSource in Test` to a non-existing directory `baseDirectory.value / "src/notests"`

**Comment by cmaeder** [comment]
@mhamilton723  can I assign this issue to you?

**Comment by mhamilton723** [comment]
Sure!

**Comment by cmaeder** [comment]
https://github.com/KWARC/MMT/blob/svn-mirror/src/tiscaf/src/test/scala/tiscaf/test/TestServerOk.scala
is resurrected

**Comment by cmaeder** [comment]
`sbt test` works now. I've also added the scala style checker http://www.scalastyle.org/, but `sbt api/scalacheck` produces 4725 warnings, but it may be suited for other modules/subprojects. 

However, I'm still looking for a tool that detects unused method arguments or bindings. (I could not yet convince IntelliJ to do this.)
