### ISSUE TITLE
svn-mirror broken

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#36]
@mhamilton723 I think you've committed wrongly to the git svn-mirror branch. Your last changes are not in svn, so the svn-mirror does no longer reflect the svn status

**Comment by cmaeder** [comment]
I've made a "new-svn-mirror". I'm not sure how to get Mark's changes into svn now.

**Comment by cmaeder** [comment]
I somehow created an svn commit (revision 2888) that is supposed to have Mark changes. However, the git commit messages are gone.

@mhamilton723 please commit directly to svn. The old branch svn-mirror can be removed now.

**Comment by cmaeder** [comment]
@mhamilton723 at the MMT meeting we decided that you should commit to svn.

To get a git repository from svn I did `git svn clone https://svn.kwarc.info/repos/MMT` that took quite some time. I've used such a repository to do `git svn dcommit` in order to push your git changes into svn.

In any case, getting your changes into svn is your responsibility.

**Comment by cmaeder** [comment]
I made a new `mirror-svn` that has as many commits as the svn has revisions

**Comment by cmaeder** [comment]
@mhamilton723 Can the old branch svn-mirror be deleted?

**Comment by mhamilton723** [comment]
Yep all clear!
