### ISSUE TITLE
pdflatex problem

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#37]
`run-pdflatex.sh MiKoMH/ACS/source/cfl/en/BNF.tex` reports this:

```
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarybackgrounds.code.tex)

! Package tikz Error: I did not find the tikz library 'mmt'. I looked for files
 named tikzlibrarymmt.code.tex and pgflibrarymmt.code.tex, but neither could be
 found in the current texmf trees..

See the tikz package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.14 \usetikzlibrary{mmt}
```

**Comment by tkw1536** [comment]
@cmaeder You need to modify the TIKZINPUTS variable to include the sty directory of localmh. See https://github.com/KWARC/localmh/blob/master/lmh/lib/extenv.py#L171-L179 for the code that does it in lmh and https://github.com/KWARC/localmh/tree/master/sty for the files themselves.

**Comment by kohlhase** [comment]
I think you mean the TEXINPUTS variable, but otherwise you are right. @cmaeder you had asked about the ```localmh/sty``` directory. That is what you need here.

**Comment by cmaeder** [comment]
sorry, TEXINPUTS was indeed wrongly set.

**Comment by cmaeder** [comment]
TEXINPUTS was already corrected in https://github.com/KWARC/MMT/commit/73e55a30f384f0327028e0749cf833868c920f29
