### ISSUE TITLE
MMT server crash

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#44]
for http://ash.eecs.jacobs-university.de:8080/errorview.html the MMT server seems to have reached its limit. The web page still showed 126963 counted error entries (but without tables). The file oaf.log shows:

```
09:50:22.446    error: (server) error in underlying server: class java.nio.channels.ClosedChannelException:null
sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:270)
sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:461)
tiscaf.HSimplePeer$class.writeToChannel(HPeer.scala:133)
tiscaf.HServer$$anon$2.writeToChannel(HServer.scala:196)
tiscaf.HWriter.write(HWriter.scala:31)
tiscaf.HWriter.write(HWriter.scala:23)
tiscaf.HWriter.writeSeq(HWriter.scala:35)
tiscaf.HIdentOut.write(HOut.scala:53)
tiscaf.HTalk.write(HTalk.scala:57)
tiscaf.HTalk.write(HTalk.scala:58)
info.kwarc.mmt.api.web.Server$$anon$1.act(Server.scala:41)
tiscaf.HSimpleLet$$anonfun$aact$1.apply$mcV$sp(HLet.scala:166)
tiscaf.HSimpleLet$$anonfun$aact$1.apply(HLet.scala:166)
tiscaf.HSimpleLet$$anonfun$aact$1.apply(HLet.scala:166)
scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by kohlhase** [comment]
Is this a memory problem?

On 28/07/15 10:05, cmaeder wrote:
>
> for http://ash.eecs.jacobs-university.de:8080/errorview.html the MMT
> server seems to have reached its limit. The web page still showed
> 126963 counted error entries (but without tables). The file oaf.log shows:
>
> |09:50:22.446    error: (server) error in underlying server: class java.nio.channels.ClosedChannelException:null
> sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:270)
> sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:461)
> tiscaf.HSimplePeer$class.writeToChannel(HPeer.scala:133)
> tiscaf.HServer$$anon$2.writeToChannel(HServer.scala:196)
> tiscaf.HWriter.write(HWriter.scala:31)
> tiscaf.HWriter.write(HWriter.scala:23)
> tiscaf.HWriter.writeSeq(HWriter.scala:35)
> tiscaf.HIdentOut.write(HOut.scala:53)
> tiscaf.HTalk.write(HTalk.scala:57)
> tiscaf.HTalk.write(HTalk.scala:58)
> info.kwarc.mmt.api.web.Server$$anon$1.act(Server.scala:41)
> tiscaf.HSimpleLet$$anonfun$aact$1.apply$mcV$sp(HLet.scala:166)
> tiscaf.HSimpleLet$$anonfun$aact$1.apply(HLet.scala:166)
> tiscaf.HSimpleLet$$anonfun$aact$1.apply(HLet.scala:166)
> scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
> scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
> scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
> scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
> scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
> scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
> scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
> |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KWARC/MMT/issues/44>.
>

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by cmaeder** [comment]
Probably, because mmt keeps all entries in memory. Florian suggested to just omit the "no error" entries.

**Comment by cmaeder** [comment]
With the change https://github.com/KWARC/MMT/commit/22dc26e43c93dfa62a24d5786401488eb68b4b1e in now worked for me.

**Comment by cmaeder** [comment]
the error re-appeared

**Comment by cmaeder** [comment]
ash is under heavy load (and even omitting "no errors" did not help). Only after deleting some errors 54819 entries are now left.

**Comment by cmaeder** [comment]
By clicking "reload" while loading the following crash can still be provoked:

```
12:03:10.92     error: (server) error in underlying server: class java.io.IOException:Broken pipe
12:03:10.92     error: sun.nio.ch.FileDispatcherImpl.write0(Native Method)
12:03:10.92     error: sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
12:03:10.92     error: sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
12:03:10.92     error: sun.nio.ch.IOUtil.write(IOUtil.java:65)
12:03:10.92     error: sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
12:03:10.92     error: tiscaf.HPeer$class.nextSelect$1(HPeer.scala:79)
12:03:10.92     error: tiscaf.HPeer$class.writeAside(HPeer.scala:86)
12:03:10.92     error: tiscaf.HServer$$anon$2.writeAside(HServer.scala:196)
...
```

**Comment by cmaeder** [comment]
it only helps to keep the load low.
