### ISSUE TITLE
allow preload customization for LaTeXML build

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#45]
In https://github.com/KWARC/localmh/issues/226 we want to customize the preloads of the LaTeXML build per MathHub repository. I would like to allow to customize that via the repository-specific ```build.msl``` file: 
* in ```build.msl``` I want to define a variable ```LaTeXML-Preloads```, which contains a list of file names and directives e.g. ```tikz.sty 'literal:\usetikzlibrary{foo}'``` (here a whitespace-separated list)
* the LaTeXML build process should then add . ```--preload=tikz.sty --preolad='literal:\usetikzlibrary{foo}'``` to the invocation of LaTeXML. (see the discussion in https://github.com/KWARC/sTeX/issues/91 for more details) 

I am not sure whether this is possible already, but we need the same functionality with the variable ```LaTeXML-paths``` and ```--path=...```.

**Comment by cmaeder** [comment]
I'm not sure if `-` is sane in environment variable names. Currently LATEXMLC, LATEXMLPROFILE, and LATEXMLEXPIRE are supported. (Furthermore STEXSTYDIR, TEXINPUTS, and PERL5LIB will be respected if given.)

The `--path` argument is currently set to `<localmh>/sty`. (I hope several  `--path=...` arguments are possible.)

**Comment by kohlhase** [comment]
> (I hope several --path=... arguments are possible.)

yes, that is intended. 


> I'm not sure if - is sane in environment variable names

just intent something sane and document it, I have little preferences. 
BTW, where are the ones you have above documented? Is there an example how to set them and where?

**Comment by cmaeder** [comment]
The above environment variables are not documented (yet), but only given in the source https://github.com/KWARC/MMT/blob/mirror-svn/src/mmt-stex/src/info/kwarc/mmt/stex/LaTeXML.scala.

LATEXMLC is the name of latexml client (`latexmlc') that can be set to an absolute path.
If LATEXMLPROFILE is not given `stex-smglom-module` is used and for `LATEXMLEXPIRE` `10` is assumed. (If `LATEXMLEXPIRE` is set to `-1` than no server `latexmls` will be used.)

**Comment by cmaeder** [comment]
It's now implemented by https://github.com/KWARC/MMT/commit/5dd916438169d318c92051391131f39ba8bdb4d0 using variables LATEXMLPRELOADS and LATEXMLPATHS.

the argument `--preload='literal:\usetikzlibrary{foo}'` results in: 

```
error: missing_file:'literal:\usetikzlibrary{foo}' Can't find package 'literal:\usetikzlibrary{foo}'
```

Without the single quotes: `Error:missing_file:tikzlibraryfoo.code.tex`

**Comment by cmaeder** [comment]
> (Furthermore STEXSTYDIR, TEXINPUTS, and PERL5LIB will be respected if given.)

In fact, these environment variables will be defined or extended by mmt.

**Comment by kohlhase** [comment]
> the argument --preload='literal:\usetikzlibrary{foo}' results in:

that is not surprising, since there is no tikz library ```foo```. that was just an example.

**Comment by kohlhase** [comment]
> The above environment variables are not documented (yet), but only given in the source

maybe now is the time to do that. Could you also give me an example how I can set them in ```build.msl```? Then I could experiment.

**Comment by cmaeder** [comment]
environment variables can be set in build.msl (or on the command line see https://github.com/KWARC/localmh/issues/232) by

```
envvar LATEXMLPRELOADS "tikz.sty"
```

or simply as bash environment variables:

```
export LATEXMLPRELOADS=tikz.sty
```

**Comment by cmaeder** [comment]
The most recent mmt.jar can always be downloaded from https://github.com/KWARC/MMT/raw/gh-pages/deploy/mmt.jar

**Comment by cmaeder** [comment]
see https://github.com/KWARC/MMT/wiki
