### ISSUE TITLE
back button not properly working when browsing MMT documentation

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#46]
After having clicked i.e. on "build" on https://svn.kwarc.info/repos/MMT/doc/html/index.html#/title.html or http://kwarc.github.io/MMT/doc/html/index.html#/title.html going back (one page) in firefox no longer works.

**Comment by cmaeder** [comment]
resolved by https://github.com/KWARC/MMT/commit/2e8abad15b28e87edb43b96148bd8fbd49758f46
(although the frames did not work on github for me https://github.com/KWARC/MMT/commit/eff8d26be6e9e5993ff969c5cd58481bdbca5dc9)

**Comment by cmaeder** [comment]
for some reason github does not serve the file http://kwarc.github.io/MMT/doc/html/_script/script.js
(though it does serve http://kwarc.github.io/MMT/doc/api/index.js)

**Comment by cmaeder** [comment]
Even http://kwarc.github.io/MMT/src/mmt-api/trunk/resources/log-html/script.js can be served, therefore I suspect `_` in the folder name `_script` is the (github-pages) problem. (Also mere directories are not served.)

**Comment by tkw1536** [comment]
@cmaeder It is indeed a github issue. Jekyll (the engine behind gh-pages that also allows templating) causes this. For details see https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/. 

The fix: Add a ```.nojekyll``` file to the gh-pages branch (could be easily done in the svn post-commit hook)

**Comment by cmaeder** [comment]
Thanks for the link. I've added a `.nojekyll` file to svn https://github.com/KWARC/MMT/commit/1e4355158aebb9f23237b3a74de75fa5e4862782
