### ISSUE TITLE
log success / failure of build targets

### ISSUE THREAD

**Issue by tkw1536** [KWARC/MMT#50]
When generating files using MMT in localmh, there is currently no feedback if a file suceeded or failed other than the messy log output given by MMT. 

I discussed it with @cmaeder and together we agreed that there should be a new logger that prints success or failure for each of the files that MMT tries to generate.

**Comment by cmaeder** [comment]
fixed by https://github.com/KWARC/MMT/commit/238752e1a00d63ecb6edb802c333657f4facd1d4
