### ISSUE TITLE
cleaning up deleted files

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#58]
since traversal only looks at existing input files, output files of deleted input files are never seen and thus never removed (via `--clean` or `--onChange` modifiers).

**Comment by cmaeder** [comment]
I see no chance to resolve this, except by writing additional clean task for whole directories

**Comment by kohlhase** [comment]
indeed, I think that this is exactly what we need. My intuition is that we know the relation between the generated files and their sources. E.g. 
xxx.omdoc <-- xxx.tex
xxx.pdf <-- xxx.tex
xxx.sms <-- xxx.tex
So when we clean pdf files, we can look whether we find their sources. If these do not exist any more, we can remove the pdfs. 
But I remember that @m-iancu had other ideas for this.

**Comment by kohlhase** [comment]
This would be very good to have for the build system. If you are fed up with parallelization, this would be something to think about.

**Comment by cmaeder** [comment]
I even delete whole (output) directories now.
