### ISSUE TITLE
inspect .tex files if they really need pre- and postamble files

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#62]
.tex files with `\documentclass` or `\begin{document}` must not be wrapped between pre- and postamble files.

**Comment by cmaeder** [comment]
@kohlhase I now check for `\documentclass` and it works for `pdf`, but `latexml` would complain that it expects `\usepackage` and `\RequirePackage` in the preamble.

**Comment by kohlhase** [comment]
this does not seem to work for ```lmh omdoc``` on ```MiKoMH/GenCS/source/legal/talks/medieninformatik.tex``` which has a ```\documentclass```. Reopening

**Comment by cmaeder** [comment]
It works after 644d713d566608d68280b96a66ce5c8599257d0e
(`latexml` no longer complains about `\usepackage`)
