### ISSUE TITLE
latexml hangs in MMT

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#67]
with a long --expire argument (600 seconds) MMT gets stuck at end the of a latexmlc call.
It only terminates after the global timeout (300 seconds) forces it (or latexmls is terminated).
Restarting MMT while latexmls is still running causes:

```
Fatal:HTTP:500 Internal Server Error
```

It seems that the scala process library can not handle processes well that start a server (or try to connect to a server).

**Comment by cmaeder** [comment]
`Fatal:HTTP:500 Internal Server Error` is only produces for `smglom/mv/source/piecewise.de.tex`.

for `piecewise.en.tex` the following is emitted:

```
element XMApp: validity error : ID cvar.2 already defined
element XMTok: validity error : ID piecewise.en.definition3.CMP1.p3.m3.1 already defined
element XMApp: validity error : ID cvar.1 already defined
element XMApp: validity error : ID cvar.0 already defined
element XMTok: validity error : ID S0.Ex1.m1.1 already defined
```

**Comment by cmaeder** [comment]
see also https://github.com/KWARC/sTeX/issues/100 and https://github.com/KWARC/sTeX/issues/107

**Comment by cmaeder** [comment]
By restarting it is also possible the provoke `Fatal:HTTP:500 Internal Server Error` for `approx.de.tex`.

**Comment by cmaeder** [comment]
@dginev 462fb2443af33f3a655f6d0c9d3475297edba76e made it work for now. The (vivid) failures still occur, but do not block the whole run (a new latexmls process will be started from my code).

The patch avoids the system call of latexmls from latexmlc.

**Comment by dginev** [comment]
Mmmm, I actually don't think you can use ```latexmls``` in the same way you use ```latexmlc```. Calling ```latexmls``` is intended to do nothing more than boot up a server - if it happens to convert the input arguments you pass the executable, you are lucky, but that can "break" at any moment.

Instead, latexmls binds to a port, to which you are expected to send an HTTP request, which is in essence equivalent to the command-line options. That's what latexmlc does under the hood.

I am quite interested to understand why latexmlc isn't terminating properly, could you figure that out?

**Comment by cmaeder** [comment]
I call both, first `latexmls` and then `latexmlc` (after one second).

Somehow `latexmls` does not exit (immediately) and therefore `latexmlc` does not exit if it calls `latexmls`.

**Comment by cmaeder** [comment]
It is a java/scala problem as it works on the shell as expected.

**Comment by dginev** [comment]
I have a vague memory that @tkw1536 had some similar issue happening in lmh when he first added latexmls support? Tom, does this issue ring a bell?

Btw, latexmlc does not depend on latexmls exiting, as latexmls will detach itself completely into its own session. Maybe you avoid calling latexmls at all and let the client executable do that to you? If you pass a non-zero ```--expire```  to latexmlc, it will start its own latexmls (if one hasn't been started already)

**Comment by cmaeder** [comment]
Somehow this "completely detaching" does not quite work. The process hangs until `latexmls` exits (due to `--expire` option).

**Comment by cmaeder** [comment]
"hang" is the wrong word. It actually processes the job, the `latexmlc` process finishes, yet the java process seems to wait for the spawned `latexmls` process to finish.

**Comment by cmaeder** [comment]
Maybe redirecting output/stderr makes a problem.

**Comment by cmaeder** [comment]
close this one in favor of #68
