### ISSUE TITLE
mmt rbuild should stay out of meta-inf

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#70]
when ```mmt rbuild``` is called at the group level, it should not build the ```meta-inf``` repository.

Generally, it seems that mmt rbuild has trouble at the group level. I would expect that it just cycles over all the MMT archives (but ```meta-inf``` is not one.

**Comment by kohlhase** [comment]
BTW, 
```
Michaels-MacBook-Pro:smglom kohlhase$ for i in `ls -d *`; do cd $i/source; lmh pdf; cd -
``` 
seems to work.

**Comment by kohlhase** [comment]
@m-iancu this may also be interestinng to you.

**Comment by cmaeder** [comment]
Currently `rbuild` does not do anything on the group level, as it does not find an archive/repository (by going up). Only a folder within a repository is traversed.

Running over `meta-inf` should not be a problem as it (usually) does not contain `.tex` files (or a `source` folder).

In the group folder one should run `mmt.jar rbuild latexml *` (latexml is internally called within the `source` folder).

**Comment by kohlhase** [comment]
Ah, thanks for the clarification, this should probably be implemented specially in ```lmh``` then. @tkw1536

**Comment by kohlhase** [comment]
> Running over meta-inf should not be a problem as it (usually) does not contain .tex files (or a source folder).

it does contain the ```pre.tex``` and so on now (but no source folder, that is true).

**Comment by cmaeder** [comment]
@tkw1536 I will add the extra traversal on the group (or higher) level.

**Comment by tkw1536** [comment]
Good, then I can make lmh gen an alias of mmt rbuild.
