### ISSUE TITLE
"no pdf generated" need not be an error

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#71]
many module signatures in smglom legitimately do not generate pdf output. I am not sure how to best deal with that.

**Comment by cmaeder** [comment]
Is there a pattern for the `no-pdf` entry in `META-INF/MANIFEST.MF`? 

Should whole repositories ignore `pdf` files for signatures?

**Comment by cmaeder** [comment]
@kohlhase what should be done, here?

**Comment by kohlhase** [comment]
I think we should just not check for no-pdf and rely only on the return value (which we now can).
