### ISSUE TITLE
weird success/failure notification

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#80]
I run ```lmh omdoc``` and get the following: 
```
latexml-result: success /path/to/localmh/MathHub/MiKoMH/GenCS/latexml/logic/en/calculus-infrules.omdoc
error: latexml: java.nio.charset.MalformedInputException: Input length = 1
latexml-result: failure /path/to/localmh/MathHub/MiKoMH/GenCS/latexml/logic/en/calculus-infrules.omdoc
```
when I look at the log file, It seems to have no problems. Is this a MMT problem?

**Comment by cmaeder** [comment]
This must be a docker problem @tkw1536. Reading the `.ltxlog` file (a UTF8- file) causes an exception in docker only. (I could try to read as ASCII though)

```
maeder@lati:/var/data/localmh/MathHub/MiKoMH/GenCS$ ../../../ext/MMT/deploy/mmt.jar rbuild latexml --force source/logic/en/calculus-infrules.tex 
latexml-result: success /var/data/localmh/MathHub/MiKoMH/GenCS/latexml/logic/en/calculus-infrules.omdoc
error: missing_file:/var/data/localmh/MathHub/MiKoMH/GenCS/source/logic/en/logical-system Can't find definitions /var/data/localmh/MathHub/MiKoMH/GenCS/source/logic/en/logical-system
error: missing_file:/var/data/localmh/MathHub/MiKoMH/GenCS/source/pl0/en/pl0-syntax Can't find definitions /var/data/localmh/MathHub/MiKoMH/GenCS/source/pl0/en/pl0-syntax
maeder@lati:/var/data/localmh/MathHub/MiKoMH/GenCS$ lmh omdoc --force source/logic/en/calculus-infrules.tex 
latexml-result: success /path/to/localmh/MathHub/MiKoMH/GenCS/latexml/logic/en/calculus-infrules.omdoc
error: missing_file:/var/data/localmh/MathHub/MiKoMH/GenCS/source/logic/en/logical-system Can't find definitions /var/data/localmh/MathHub/MiKoMH/GenCS/source/logic/en/logical-system
error: missing_file:/var/data/localmh/MathHub/MiKoMH/GenCS/source/pl0/en/pl0-syntax Can't find definitions /var/data/localmh/MathHub/MiKoMH/GenCS/source/pl0/en/pl0-syntax
error: latexml: java.nio.charset.MalformedInputException: Input length = 1
latexml-result: failure /path/to/localmh/MathHub/MiKoMH/GenCS/latexml/logic/en/calculus-infrules.omdoc
```

**Comment by tkw1536** [comment]
I can try to set the locale inside docker manually maybe that will help

**Comment by cmaeder** [comment]
```
root@hostname:/var/data/localmh/MathHub/MiKoMH/GenCS# locale -a
C
C.UTF-8
POSIX
```

Setting LC_ALL to `C.UTF-8` did not help.

**Comment by tkw1536** [comment]
I was thinking just UTF-8 and running the appropriate local-gen

**Comment by cmaeder** [comment]
I don't get rid of this error (even for `LANG=en_US.UTF-8`)

**Comment by cmaeder** [comment]
If I call mmt within docker (and `LANG`) the error is gone. So `lmh` provides the wrong environment for mmt.

**Comment by tkw1536** [comment]
Where did you try to set it inside docker and it did not work?

**Comment by cmaeder** [comment]
I set in `~/.bashrc` for root.

**Comment by cmaeder** [comment]
Reading as iso-latin has the disadvantage that utf-8 characters are turned into bad  characters for standard output or `.err` files. i.e. `XMLText[“documentkeysid=` is turned into `XMLText[â<U+0080><U+009C>documentkeysid=`

**Comment by cmaeder** [comment]
lmh turns this into `[XMLText[???documentkeysid=`

**Comment by cmaeder** [comment]
The weird/contradicting notifications are gone. Changing the encoding is a different issue depending on https://github.com/KWARC/localmh/issues/257

**Comment by cmaeder** [comment]
I always assume now UTF-8 as standard encoding https://github.com/KWARC/MMT/commit/3391ec32f5a5be6d8599749efbd62dbdebed16f1
