### ISSUE TITLE
target planetary doesn't work in rbuild

### ISSUE THREAD

**Issue by m-iancu** [KWARC/MMT#83]
The classes are in mmt.jar but rbuild doesn't seem to be aware of it. I think the map of target to classes should add `planetary` -> `info.kwarc.mmt.planetary.PlanetaryPresenter` 
also `html` -> `info.kwarc.mmt.api.archives.HTMLExporter`
and `svg` -> `info.kwarc.mmt.api.archives.GraphViz` 

Then I can fully switch to lmh rbuild for building MathHub.

**Comment by cmaeder** [comment]
@m-iancu can you test it?

**Comment by m-iancu** [comment]
It seems to work but there is no ouput, it just exists as if it did nothing. But I checked the files and they are indeed regenerated.
