### ISSUE TITLE
MMT/physics-units has lib/preamble

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#85]
/Users/kohlhase/localmh/MathHub/MMT/physics-units/lib/preamble.tex
that must be an error, right?

**Comment by kohlhase** [comment]
hmmm, MathHub/tps/tps has a lib with preamble as well, but no meta-inf repos. What to do here?

**Comment by kohlhase** [comment]
I have to correct myself about the tps. It does have a meta-inf repos. I have thoroughly reorganized it.

**Comment by cmaeder** [comment]
I've removed `MMT/physics-units/lib` since this repository does not contain `.tex` files

**Comment by kohlhase** [comment]
OK, closing
