### ISSUE TITLE
mmt rbuild pdf should be quiet

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#86]
We should make ```mmt rbuild pdf``` quiet (there is an option for this: ```-interaction=batchmode```) unless ```--pipe-worker-output``` is given.

**Comment by cmaeder** [comment]
My commit https://github.com/KWARC/MMT/commit/2a29ca5d94f1c57de9f160f0801de20cc8ea4817 for #78 wrongly switched on the worker output for pdflatex permanently (it was only supposed to switch it off for latexml - my bad). The commit 0c1df9352d88777877e03a44f029d65fb23236ae (with a wrong issue reference to #87) fixes this.

So pdf should be now quiet again. 

I've also tested `batchmode`, but that always failed with:

```
  restricted \write18 enabled.
 %&-line parsing enabled.
**\documentclass{smglom}
! Emergency stop.
<*> \documentclass{smglom}
                          
*** (job aborted, no legal \end found)
```
