### ISSUE TITLE
rbuild omdoc still times out on problems

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#87]
We have fixed one error in sTeX, but I still get a timeout and no log file that I could check. 
```
Michaels-MacBook-Pro:en kohlhase$ lmh omdoc --force inductive-function-1.tex 
error: latexml: java.util.concurrent.TimeoutException: Futures timed out after [300 seconds]
latexml-result: failure /path/to/localmh/MathHub/MiKoProblems/GenCS/latexml/dmath/en/inductive-function-1.omdoc
Michaels-MacBook-Pro:en kohlhase$ ls -l /path/to/localmh/MathHub/MiKoProblems/GenCS/latexml/dmath/en/inductive-function-1.omdoc
ls: /path/to/localmh/MathHub/MiKoProblems/GenCS/latexml/dmath/en/inductive-function-1.omdoc: No such file or directory
```

**Comment by cmaeder** [comment]
please ignore the wrong reference for #86

**Comment by cmaeder** [comment]
I cannot reproduce the timeout on my machine. I observed it to fail and to succeed. The failure (with `--pipe-worker-output` and using mmt directly) is:

```
archive: [source -> latexml] /var/data/localmh/MathHub/MiKoProblems/GenCS/source/dmath/en/inductive-function-1.tex -> /var/data/localmh/MathHub/MiKoProblems/GenCS/latexml/dmath/en/inductive-function-1.omdoc
element XMTok: validity error : ID I3.I5.i2.p1.p1.m1.1 already defined
element XMTok: validity error : ID I3.I5.i2.p1.p1.m1.2 already defined
error: latexml: no omdoc created
latexml-result: failure /var/data/localmh/MathHub/MiKoProblems/GenCS/latexml/dmath/en/inductive-function-1.omdoc
element XMTok: validity error : ID I3.I5.i2.p1.p1.m1.1 already defined
element XMTok: validity error : ID I3.I5.i2.p1.p1.m1.2 already defined
Fatal:HTTP:500 Internal Server Error
```

Both latexmls and latexmlc report these `validity error`s that are specific for my Ubuntu 15.04 (Vivid) see https://github.com/KWARC/sTeX/issues/100. Sometimes only the first validity error appears. 
Sometimes I only get the fatal `500 Internal Server Error` (and now I can no longer reproduce the success). I'll try on ash.

**Comment by cmaeder** [comment]
It works fine under ash. (I could not test the docker yet)

**Comment by cmaeder** [comment]
Meanwhile, I've downgraded my `libxml2` via `apt-get install libxml2=2.9.1+dfsg1-3ubuntu4` after adding `deb http://de.archive.ubuntu.com/ubuntu/ trusty main` to my `/etc/apt/sources.list`. (`utopic` no longer exists.)

It works for me successfully also using the docker.

**Comment by cmaeder** [comment]
see #84

**Comment by cmaeder** [comment]
I can reproduce this now:

```
maeder@lati:/var/data/localmh/MathHub$ /var/data/localmh/ext/MMT/deploy/mmt.jar rbuild latexml --force MiKoProblems/GenCS/source/dmath/en/injective-function.tex 
error: latexml: java.util.concurrent.TimeoutException: Futures timed out after [300 seconds]
latexml-result: failure /var/data/localmh/MathHub/MiKoProblems/GenCS/latexml/dmath/en/injective-function.omdoc
```

**Comment by cmaeder** [comment]
`latexmls` has actually 100% CPU for more than 4 minutes. (I'll try to get some verbose output.)

**Comment by cmaeder** [comment]
With --timeout=800 it goes through, although with an internal fatal `timedout Conversion`

**Comment by kohlhase** [comment]
I wonder why that takes sooooo long, but after I have fixed the underlying bug with the ```tikzinput``` package, things seem back on track.

**Comment by cmaeder** [comment]
Currently I do not pass the timeout (for conversion) to latexml. In a test where I did this one hour was not long enough. It must be a latexml problem.
