### ISSUE TITLE
build process for tikz files in sTeX

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#88]
In sTeX we have the ```.../tikz``` directories, and I said I want ```lmh omdoc``` to stay out of them. That is correct, but I really want a custom build process to run on these directories: 
* generate the file ```localfiles.tex``` 
* for each file ```xxx.tex``` run ```pdflatex xxx.tex```
* and then convert ```convert xxx.pdf xxx.svg```.
And redo the latter whenever ```xxx.tex``` or one of its dependencies has changed.

The generated svg files are needed for ```lmh omdoc``` for the modules that include ```xxx.tex```.

**Comment by kohlhase** [comment]
Actually, if it helps, the ```convert``` is not really necessary, we can let LaTeXML do that.

**Comment by cmaeder** [comment]
`rbuild tikzpdf ...` will now create `.pdf` files for `.tex` files within a `tikz` folder. (I assume that `tikz` folders are leaf folders, without subfolders containing .tex files)

If you tell me the command to convert `.pdf` to `.svg` I could make a separate target (that could be combined via `_` for `rbuild`)

**Comment by kohlhase** [comment]
Wonderful, thanks. 

I am testing it and it seems to work well (and finds quite a few errors). 

Could you make this a prerequisite of the ```rbuild latexml``` build target? 

Does this make the ```localpaths.tex``` that are necessary?

**Comment by cmaeder** [comment]
Yes, files `tikz/localpaths.tex` are created (if they do not exist).

How should  I make a prerequisite for the .omdoc files? Should all .pdf files in a `tikz` subfolder be dependencies for an .omdoc files? Do you need .svg files? Meanwhile you could try `rbuild tikzpdf_latexml`.

**Comment by kohlhase** [comment]
BTW, the TIKZ files are subject to the usual dependencies for sTeX files. 
On the other hand, whenever there is a ```\tikzinput{<path>}```, ```\ctikzinput{<path>}```, in a file then it depends on the TIKZ PDF ```<path>.pdf``` and if there is a ```\mhtikzinput{<repospath>}```, ```\cmhtikzinput[<mhrepos>]{<repospath>}```, then it depends on the TIKZ PDF ```MathHuB{<mhrepos>/source/<repospath>``` in the usual way.

**Comment by cmaeder** [comment]
The target is now call `tikzsvg`! I think, it does not work with `lmh` because `convert` is not installed.  Dependencies are not yet extracted.

**Comment by cmaeder** [comment]
In your repos I did not find any usages of `\tikzinput` and `\ctikzinput` (only the `mh` versions)

**Comment by kohlhase** [comment]
Indeed that is true. But the others may still exist somewhere outside of MathHub.

**Comment by cmaeder** [comment]
To install `convert` call `apt-get install imagemagick` in the root shell obtained by `lmh docker sshell`
(@tkw1536 maybe you can add `imagemagick` to the lmh docker file, or wait until `convert` is no longer needed because `latexml` handles `tikz` files)

**Comment by kohlhase** [comment]
Should I add the tikzsvg process to all the GenCS build msl files?

**Comment by cmaeder** [comment]
No, I don't use these build.msl files. `lmh mmt rbuild tikzsvg` should do the job. I'm also not sure if `tikzsvg` is settled now (as you wanted to try out latexml directly).

**Comment by kohlhase** [comment]
I think we should turn this on, it is "good enough", and the latexml version will have to mature a bit, we can always exchange this later.

**Comment by kohlhase** [comment]
> No, I don't use these build.msl files.

is anybody still using them? Could they be deleted?

**Comment by cmaeder** [comment]
@m-iancu the build.msl file contain commands for `stex-omdoc` and exports, but this can be called via lmh, too:

```
lmh mmt rbuild stex-omdoc --force smglom/mv/
```

However, `stex-omdoc` without the option `--force` or the option (i.e. `--depsFirst`) is not really supported. (Also `update` needs to build twice in case of doubt.)

**Comment by cmaeder** [comment]
I made a new issue for `stex-omdoc` #91 and close this one
