### ISSUE TITLE
rbuild sms should absolutize mh paths. 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#92]
Currently ```rbuild sms``` just copies over ```\importmhmodule``` to the ```sms``` file. But I would like to have the paths absolutized. Let me make an example: 

We are in repos ```MiKoMH/GenCS``` which has the absolute path ```/path/to/localmh/MathHub/MiKoMH/GenCS``` and we have a file with repository path ```foo/en/bar.tex```, which translates to an absolute path ```/path/to/localmh/MathHub/MiKoMH/GenCS/source/foo/en/bar.tex```.

So in ```bar.tex```, we see 
```
\importmhmodule[path=foobar/en/baz]{baz}
```
then I would like to see in the file ```bar.sms``` (note the missing ```mh```)
```
\importmodule[load=/path/to/localmh/MathHub/MiKoMH/GenCS/source/foobar/en/baz]{baz}
```
Similarly, if we see in  ```bar.tex```
```
\importmhmodule[repos=MiKoProblems/CompLog,path=foobar/en/baz]{baz}
```
then I would like to see in the file ```bar.sms``` (note the missing ```mh```)
```
\importmodule[load=/path/to/localmh/MathHub/MiKoProblems/CompLog/source/foobar/en/baz]{baz}
```
This would make my LaTeX coding life much easier. I think that MMT has all the information it needs for this

**Comment by kohlhase** [comment]
hmmm, that seems to work well. I think we should also absolutize ```\gimport``` and friends. I.g. 
If we are in ```MathHub/smglom/foo```, then 
```
\gimport{bar}
```
should become 
```
\importmodule[load=/path/to/localmh/MathHub/smglom/foo/source/bar}{bar}
``` 
and 
```
\gimport[smglom/baz]{bar}
``` 
should become 
```
\importmodule[load=/path/to/localmh/MathHub/smglom/baz/source/bar}{bar}
``` 
All that is completely analogous to the change already done.

**Comment by cmaeder** [comment]
should work now

**Comment by kohlhase** [comment]
Sorry, I was wrong with my specification. For ```\gimport``` we have to add a key ```ext=tex```, e.g. 

```
\gimport{bar}
```
should become
```
\importmodule[load=/path/to/localmh/MathHub/smglom/foo/source/bar,ext=tex}{bar}
```

**Comment by cmaeder** [comment]
see https://github.com/KWARC/MMT/commit/493dd2a85bf44653a97d823d6c4217b2ead77e16

**Comment by kohlhase** [comment]
I guess I get what I asked for: ```\mhcurrentmodule```, unfortunately, what I need is ```\mhcurrentrepos```. Sorry for the nuiscance.
