### ISSUE TITLE
multiple no-omdoc fields in MANIFEST.MF?

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#93]
Are they allowed and cumulated? If yes, please answer and close, if no, please implement (or argue against). 

I made one in ```MathHub/MiKoMH/AI/META-INF/MANIFEST.MH```.

**Comment by cmaeder** [comment]
Currently, multiples patterns following `no-omdoc` (or `no-pdf`) must be separated by spaces (not by commas)

**Comment by cmaeder** [comment]
see #32 for build exceptions

**Comment by cmaeder** [comment]
The `MANIFEST.MF` contains a key value map, the last entry for a repeated key "wins".

**Comment by cmaeder** [comment]
I could accumulate entries "old entry + space + new entry", but this may not make sense for all keys.

**Comment by cmaeder** [comment]
May this change helps to sort out some spurious duplicate keys
