### ISSUE TITLE
archive detection is unreliable

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#94]
MMT detects an archive by checking for a file `META-INF/MANIFEST.MF` (or just `MANIFEST.MF`).

However, on a case-insensitive file system (i.e. Mac), a group directory containing a `meta-inf` repository with a `MANIFEST.MF` file is wrongly detected as an archive. 

This causes `mmt rbuild` to do nothing in such a group directory.

**Comment by cmaeder** [comment]
@kohlhase Can you check if it now (after https://github.com/KWARC/MMT/commit/90bb5940b841e6181000bc77601c1f6cd572c166) works on your mac?

**Comment by kohlhase** [comment]
seems to work, closing.

**Comment by cmaeder** [comment]
@kohlhase please (after updating) run `mmt "log+ backend ; rbuild sms --force"` in `MiKoMH` to really see if `META-INF/MANIFEST.MF` files are properly detected

**Comment by kohlhase** [comment]
I did that, and I guess what you are looking for is this, right? 
```
backend: manifest file: /Users/kohlhase/localmh/MathHub/MiKoMH/meta-inf/MANIFEST.MF
backend: /Users/kohlhase/localmh/MathHub/MiKoMH/meta-inf/MANIFEST.MF does not contain id, skipping this archive
backend: manifest file: /Users/kohlhase/localmh/MathHub/MiKoMH/talks/META-INF/MANIFEST.MF
backend: adding archive defined by /Users/kohlhase/localmh/MathHub/MiKoMH/talks/META-INF/MANIFEST.MF
backend: adding storage archive /Users/kohlhase/localmh/MathHub/MiKoMH/talks
```

**Comment by cmaeder** [comment]
Actually, no. I was expecting `"manifest: " + t1 + "\ndoes not match: " + t2` where t1 contains `META_INF` and t2 contains `meta-inf` (to avoid matching by the wrong case).

As I saw it works if `id` is given in `meta-inf/MANIFEST.MF`, but the same message should also be displayed without `id`! (Your log snippet is only displayed later)
