### ISSUE TITLE
missing stex dependencies

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#97]
in `HelloWorld` `lmh pdf --depsFirst hwexam/source/assignments/a1.tex` fails due to a missing `.sms` file that is not recognized as dependency. `a1.tex` contains `\includemhproblem[pts=30,mhrepos=HelloWorld/hwexam]{problems/hello-stex-smglom}` that is not considered yet. (The currently considered keys are  "guse", "gimport", "usemhmodule", "importmhmodule", "begin\\{modnl\\}",  "mhinputref", "mhtikzinput", "cmhtikzinput", "tikzinput", "ctikzinput".)

@kohlhase Which other keywords are missing beside `\includemhproblem`?

**Comment by kohlhase** [comment]
I actually think that is all all.

**Comment by cmaeder** [comment]
https://travis-ci.org/KWARC/localmh/builds/92687511 shows that all .pdf files are created successfully.

**Comment by kohlhase** [comment]
very good news.
