### ISSUE TITLE
Instate lmh 'xml'? 

### ISSUE THREAD

**Issue by angerhang** [KWARC/MMT#99]
As Deyan pointed out in KWARC/sTeX#190, I think it would be helpful if we have a command 'lmh xml' that only generates *.xml without calling the post-processor for debugging purposes.

**Comment by kohlhase** [comment]
Maybe the best say of doing that is to pass generic attributes on to LaTeXML, in this case ```--nopost``` would be enough. I am not sure whether that is already possible.

**Comment by cmaeder** [comment]
I don't quite see yet, in what way I need to change my current `latexmlc` call in order to produce `xml` instead of `omdoc`.

**Comment by cmaeder** [comment]
My current `latexmlc` call is:

```
maeder@lati:/var/data/localmh/MathHub/smglom/mv$ mmt.jar "log+ latexml ; make latexml --force source/equal.en.tex" 
latexml: environment variable LATEXMLC is not set using "latexmlc"
latexml: /var/data/localmh/MathHub/smglom/mv/source/equal.en.tex: BuildDependency(latexml,archive /var/data/localmh/MathHub/smglom/mv,equal.tex)
latexml: /var/data/localmh/ext/perl5lib/bin/latexmlc /var/data/localmh/MathHub/smglom/mv/source/equal.en.tex
latexml:  --profile=stex-smglom-module
latexml:  --path=/var/data/localmh/sty
latexml:  --destination=/var/data/localmh/MathHub/smglom/mv/latexml/equal.en.omdoc
latexml:  --log=/var/data/localmh/MathHub/smglom/mv/latexml/equal.en.ltxlog
latexml:  --preamble=/var/data/localmh/MathHub/smglom/meta-inf/lib/pre.en.tex
latexml:  --postamble=/var/data/localmh/MathHub/smglom/meta-inf/lib/post.tex
latexml:  --expire=600
latexml:  --port=4227
latexml-result: success /var/data/localmh/MathHub/smglom/mv/latexml/equal.en.omdoc
```

What should I omit or change to get `xml`?

**Comment by cmaeder** [comment]
BTW, I still see only "(written )" in `equal.en.omdoc`

**Comment by kohlhase** [comment]
just add a ```--nopost``` to the call.

**Comment by cmaeder** [comment]
It is implemented and to be called by `lmh omdoc --force --nopost`. The `xml` output is written to the very same `.omdoc` file, currently. (For a different extension I need to make a separate target, or simply fail producing omdoc)
